### ISSUE TITLE
Loader problem.

### ISSUE THREAD

**Issue by gon250** [eanplatter/react-starter#2]
Hello, 

I'm trying to get running your react starter app, but I'm getting the following error: 

![image](https://cloud.githubusercontent.com/assets/1652286/11422332/f4ddbd6c-9432-11e5-93a8-078067288d38.png)

any idea why? and how can I fix it? I'm not sure if it's a bug or my fault.

Thanks!

**Comment by eanplatter** [comment]
What this error means is webpack is trying to read ES6 `import` syntax without ever running it through the babel loader. It might mean there is some kind of dependency missing.

You did run `npm install` in your command line after cloning, right? I will see if I can reproduce the error on a clean machine to see if I neglected to mention some global deps that might be needed.

**Comment by eanplatter** [comment]
I guess if you didn't `npm install` you'd have other problems than that.

In the **_webpack.config.js_** file you have a line that looks like this:

``` javascript
include: __dirname + '/app'
```

I was able to reproduce this error if I removed `__dirname`, so maybe the node `__dirname` variable is messed up.

You could just replace `__dirname + '/app'` with your directory's total file path (hacky temporary solution):

``` javascript
include: '/c/MMDATA/Gonzalo-dev/react-starter/app'
```

Also, it might be a windows problem, I'll have access to a windows machine later today and I'll check it out.

**Comment by gon250** [comment]
Yep, I've execute `npm install` before to do anything. I think you are right and I'm missing some packages, make sense. 

I'm trying to get it working at work and I think the proxy did not let me download some of the packages.. so I'll try tonight in my mac and let see. sorry to bother you and thanks!
